In [48]:
## Importation des bibliothèques ##

import matplotlib.pyplot as plt 
import numpy as np 
import pandas as pd
import plotly.express as px
import seaborn as sns

In [49]:
## Importation du Dataset ##

jo = pd.read_csv("athlete_events.csv")

In [50]:
## Visualisation du Dataset ##

jo

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271111,135569,Andrzej ya,M,29.0,179.0,89.0,Poland-1,POL,1976 Winter,1976,Winter,Innsbruck,Luge,Luge Mixed (Men)'s Doubles,NaN
271112,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN
271113,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN
271114,135571,Tomasz Ireneusz ya,M,30.0,185.0,96.0,Poland,POL,1998 Winter,1998,Winter,Nagano,Bobsleigh,Bobsleigh Men's Four,NaN
271115,135571,Tomasz Ireneusz ya,M,34.0,185.0,96.0,Poland,POL,2002 Winter,2002,Winter,Salt Lake City,Bobsleigh,Bobsleigh Men's Four,NaN

In [51]:
## Visualisation des différentes informations de l'ensemble de données, 
## comme le type de données (numérique, catégorielle) : colonne "Dtype",
## comme les valeurs manquantes : colonne "Non-Null Count",
## etc.... ##

jo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271116 entries, 0 to 271115
Data columns (total 15 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   ID      271116 non-null  int64
 1   Name    271116 non-null  object
 2   Sex     271116 non-null  object
 3   Age     261642 non-null  float64
 4   Height  210945 non-null  float64
 5   Weight  208241 non-null  float64
 6   Team    271116 non-null  object
 7   NOC     271116 non-null  object
 8   Games   271116 non-null  object
 9   Year    271116 non-null  int64
 10  Season  271116 non-null  object
 11  City    271116 non-null  object
 12  Sport   271116 non-null  object
 13  Event   271116 non-null  object
 14  Medal   39783 non-null   object
dtypes: float64(3), int64(2), object(10)
memory usage: 31.0+ MB

In [52]:
## Suppression des lignes contenant "Winter" dans la colonne "Season" ##

jo = jo[jo['Season'] != 'Winter']
jo

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
26,8,"Cornelia ""Cor"" Aalten (-Strannood)",F,18.0,168.0,NaN,Netherlands,NED,1932 Summer,1932,Summer,Los Angeles,Athletics,Athletics Women's 100 metres,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271106,135565,Fernando scar Zylberberg,M,27.0,168.0,76.0,Argentina,ARG,2004 Summer,2004,Summer,Athina,Hockey,Hockey Men's Hockey,NaN
271107,135566,"James Francis ""Jim"" Zylker",M,21.0,175.0,75.0,United States,USA,1972 Summer,1972,Summer,Munich,Football,Football Men's Football,NaN
271108,135567,Aleksandr Viktorovich Zyuzin,M,24.0,183.0,72.0,Russia,RUS,2000 Summer,2000,Summer,Sydney,Rowing,Rowing Men's Lightweight Coxless Fours,NaN
271109,135567,Aleksandr Viktorovich Zyuzin,M,28.0,183.0,72.0,Russia,RUS,2004 Summer,2004,Summer,Athina,Rowing,Rowing Men's Lightweight Coxless Fours,NaN
271110,135568,Olga Igorevna Zyuzkova,F,33.0,171.0,69.0,Belarus,BLR,2016 Summer,2016,Summer,Rio de Janeiro,Basketball,Basketball Women's Basketball,NaN

In [53]:
## Suppression de la colonne "Games" qui fait doublon avec les infos des colonnes "Year" et "Season" ##

jo = jo.drop("Games", axis=1)
jo

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
26,8,"Cornelia ""Cor"" Aalten (-Strannood)",F,18.0,168.0,NaN,Netherlands,NED,1932,Summer,Los Angeles,Athletics,Athletics Women's 100 metres,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271106,135565,Fernando scar Zylberberg,M,27.0,168.0,76.0,Argentina,ARG,2004,Summer,Athina,Hockey,Hockey Men's Hockey,NaN
271107,135566,"James Francis ""Jim"" Zylker",M,21.0,175.0,75.0,United States,USA,1972,Summer,Munich,Football,Football Men's Football,NaN
271108,135567,Aleksandr Viktorovich Zyuzin,M,24.0,183.0,72.0,Russia,RUS,2000,Summer,Sydney,Rowing,Rowing Men's Lightweight Coxless Fours,NaN
271109,135567,Aleksandr Viktorovich Zyuzin,M,28.0,183.0,72.0,Russia,RUS,2004,Summer,Athina,Rowing,Rowing Men's Lightweight Coxless Fours,NaN
271110,135568,Olga Igorevna Zyuzkova,F,33.0,171.0,69.0,Belarus,BLR,2016,Summer,Rio de Janeiro,Basketball,Basketball Women's Basketball,NaN

In [54]:
## suppression des lignes contenant "NA" ##

jo = jo.dropna()
jo

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Year,Season,City,Sport,Event,Medal
41,17,Paavo Johannes Aaltonen,M,28.0,175.0,64.0,Finland,FIN,1948,Summer,London,Gymnastics,Gymnastics Men's Individual All-Around,Bronze
42,17,Paavo Johannes Aaltonen,M,28.0,175.0,64.0,Finland,FIN,1948,Summer,London,Gymnastics,Gymnastics Men's Team All-Around,Gold
44,17,Paavo Johannes Aaltonen,M,28.0,175.0,64.0,Finland,FIN,1948,Summer,London,Gymnastics,Gymnastics Men's Horse Vault,Gold
48,17,Paavo Johannes Aaltonen,M,28.0,175.0,64.0,Finland,FIN,1948,Summer,London,Gymnastics,Gymnastics Men's Pommelled Horse,Gold
50,17,Paavo Johannes Aaltonen,M,32.0,175.0,64.0,Finland,FIN,1952,Summer,Helsinki,Gymnastics,Gymnastics Men's Team All-Around,Bronze
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271078,135553,Galina Ivanovna Zybina (-Fyodorova),F,25.0,168.0,80.0,Soviet Union,URS,1956,Summer,Melbourne,Athletics,Athletics Women's Shot Put,Silver
271080,135553,Galina Ivanovna Zybina (-Fyodorova),F,33.0,168.0,80.0,Soviet Union,URS,1964,Summer,Tokyo,Athletics,Athletics Women's Shot Put,Bronze
271082,135554,Bogusaw Zych,M,28.0,182.0,82.0,Poland,POL,1980,Summer,Moskva,Fencing,"Fencing Men's Foil, Team",Bronze
271102,135563,Olesya Nikolayevna Zykina,F,19.0,171.0,64.0,Russia,RUS,2000,Summer,Sydney,Athletics,Athletics Women's 4 x 400 metres Relay,Bronze
271103,135563,Olesya Nikolayevna Zykina,F,23.0,171.0,64.0,Russia,RUS,2004,Summer,Athina,Athletics,Athletics Women's 4 x 400 metres Relay,Silver

In [55]:
## Suppression des sports collectifs ou trop ancien ##

spcol = ['Art Competitions', 'Baseball', 'Basketball', 'Beach Volleyball', 'Football', 'Handball', 'Hockey', 'Ice Hockey', 'Lacrosse', 'Rowing',
        'Rugby', 'Rugby Sevens', 'Softball', 'Synchronized Swimming', 'Tug-Of-War', 'Volleyball', 'Water Polo']

jo2 = jo[~jo['Sport'].isin(spcol)]

jo2

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Year,Season,City,Sport,Event,Medal
41,17,Paavo Johannes Aaltonen,M,28.0,175.0,64.0,Finland,FIN,1948,Summer,London,Gymnastics,Gymnastics Men's Individual All-Around,Bronze
42,17,Paavo Johannes Aaltonen,M,28.0,175.0,64.0,Finland,FIN,1948,Summer,London,Gymnastics,Gymnastics Men's Team All-Around,Gold
44,17,Paavo Johannes Aaltonen,M,28.0,175.0,64.0,Finland,FIN,1948,Summer,London,Gymnastics,Gymnastics Men's Horse Vault,Gold
48,17,Paavo Johannes Aaltonen,M,28.0,175.0,64.0,Finland,FIN,1948,Summer,London,Gymnastics,Gymnastics Men's Pommelled Horse,Gold
50,17,Paavo Johannes Aaltonen,M,32.0,175.0,64.0,Finland,FIN,1952,Summer,Helsinki,Gymnastics,Gymnastics Men's Team All-Around,Bronze
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271078,135553,Galina Ivanovna Zybina (-Fyodorova),F,25.0,168.0,80.0,Soviet Union,URS,1956,Summer,Melbourne,Athletics,Athletics Women's Shot Put,Silver
271080,135553,Galina Ivanovna Zybina (-Fyodorova),F,33.0,168.0,80.0,Soviet Union,URS,1964,Summer,Tokyo,Athletics,Athletics Women's Shot Put,Bronze
271082,135554,Bogusaw Zych,M,28.0,182.0,82.0,Poland,POL,1980,Summer,Moskva,Fencing,"Fencing Men's Foil, Team",Bronze
271102,135563,Olesya Nikolayevna Zykina,F,19.0,171.0,64.0,Russia,RUS,2000,Summer,Sydney,Athletics,Athletics Women's 4 x 400 metres Relay,Bronze
271103,135563,Olesya Nikolayevna Zykina,F,23.0,171.0,64.0,Russia,RUS,2004,Summer,Athina,Athletics,Athletics Women's 4 x 400 metres Relay,Silver

In [56]:
## Ajout du sport Rowing pour les épreuves 'single' ##

rowing_single = jo[(jo["Sport"] == "Rowing") & (jo["Event"].str.contains("single", case=False))]
jo = pd.concat([rowing_single, jo2])
jo

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Year,Season,City,Sport,Event,Medal
8318,4587,Yelena Petrovna Antonova,F,23.0,180.0,78.0,Soviet Union,URS,1976,Summer,Montreal,Rowing,Rowing Women's Single Sculls,Bronze
17710,9421,Jutta Behrendt (Hampe-),F,27.0,181.0,75.0,East Germany,GDR,1988,Summer,Seoul,Rowing,Rowing Women's Single Sculls,Gold
28647,14846,Annelies Bredael,F,27.0,175.0,68.0,Belgium,BEL,1992,Summer,Barcelona,Rowing,Rowing Women's Single Sculls,Silver
29717,15344,Kajetan Tomasz Broniewski,M,29.0,187.0,92.0,Poland,POL,1992,Summer,Barcelona,Rowing,Rowing Men's Single Sculls,Bronze
32883,16915,Everard Burnside Butler,M,26.0,183.0,72.0,Canada,CAN,1912,Summer,Stockholm,Rowing,Rowing Men's Single Sculls,Bronze
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271078,135553,Galina Ivanovna Zybina (-Fyodorova),F,25.0,168.0,80.0,Soviet Union,URS,1956,Summer,Melbourne,Athletics,Athletics Women's Shot Put,Silver
271080,135553,Galina Ivanovna Zybina (-Fyodorova),F,33.0,168.0,80.0,Soviet Union,URS,1964,Summer,Tokyo,Athletics,Athletics Women's Shot Put,Bronze
271082,135554,Bogusaw Zych,M,28.0,182.0,82.0,Poland,POL,1980,Summer,Moskva,Fencing,"Fencing Men's Foil, Team",Bronze
271102,135563,Olesya Nikolayevna Zykina,F,19.0,171.0,64.0,Russia,RUS,2000,Summer,Sydney,Athletics,Athletics Women's 4 x 400 metres Relay,Bronze
271103,135563,Olesya Nikolayevna Zykina,F,23.0,171.0,64.0,Russia,RUS,2004,Summer,Athina,Athletics,Athletics Women's 4 x 400 metres Relay,Silver

In [57]:
## Suppression des épreuves collectives ##

epcol = ['Synchronized', 'Doubles', 'Fours', 'Team', 'Relay', 'Group', 'Pairs', 'Quadruple', 'Three', 'Two', 'Mixed', 'Skiff', 'Tandem']

jo = jo[jo['Event'].apply(lambda x: not any(term in x for term in epcol))]

jo

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Year,Season,City,Sport,Event,Medal
8318,4587,Yelena Petrovna Antonova,F,23.0,180.0,78.0,Soviet Union,URS,1976,Summer,Montreal,Rowing,Rowing Women's Single Sculls,Bronze
17710,9421,Jutta Behrendt (Hampe-),F,27.0,181.0,75.0,East Germany,GDR,1988,Summer,Seoul,Rowing,Rowing Women's Single Sculls,Gold
28647,14846,Annelies Bredael,F,27.0,175.0,68.0,Belgium,BEL,1992,Summer,Barcelona,Rowing,Rowing Women's Single Sculls,Silver
29717,15344,Kajetan Tomasz Broniewski,M,29.0,187.0,92.0,Poland,POL,1992,Summer,Barcelona,Rowing,Rowing Men's Single Sculls,Bronze
32883,16915,Everard Burnside Butler,M,26.0,183.0,72.0,Canada,CAN,1912,Summer,Stockholm,Rowing,Rowing Men's Single Sculls,Bronze
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270986,135508,Vera Igorevna Zvonaryova,F,23.0,172.0,59.0,Russia,RUS,2008,Summer,Beijing,Tennis,Tennis Women's Singles,Bronze
271032,135535,Claudia Antoinette Zwiers,F,22.0,181.0,78.0,Netherlands,NED,1996,Summer,Atlanta,Judo,Judo Women's Middleweight,Bronze
271076,135553,Galina Ivanovna Zybina (-Fyodorova),F,21.0,168.0,80.0,Soviet Union,URS,1952,Summer,Helsinki,Athletics,Athletics Women's Shot Put,Gold
271078,135553,Galina Ivanovna Zybina (-Fyodorova),F,25.0,168.0,80.0,Soviet Union,URS,1956,Summer,Melbourne,Athletics,Athletics Women's Shot Put,Silver
271080,135553,Galina Ivanovna Zybina (-Fyodorova),F,33.0,168.0,80.0,Soviet Union,URS,1964,Summer,Tokyo,Athletics,Athletics Women's Shot Put,Bronze

In [58]:
## Suppression des 1ere infos de la colonne "Event" jusqu'à " 's " ##

jo.loc[:, 'Event'] = jo['Event'].str.split("'s", n=1).str[1].str.strip()
jo

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Year,Season,City,Sport,Event,Medal
8318,4587,Yelena Petrovna Antonova,F,23.0,180.0,78.0,Soviet Union,URS,1976,Summer,Montreal,Rowing,Single Sculls,Bronze
17710,9421,Jutta Behrendt (Hampe-),F,27.0,181.0,75.0,East Germany,GDR,1988,Summer,Seoul,Rowing,Single Sculls,Gold
28647,14846,Annelies Bredael,F,27.0,175.0,68.0,Belgium,BEL,1992,Summer,Barcelona,Rowing,Single Sculls,Silver
29717,15344,Kajetan Tomasz Broniewski,M,29.0,187.0,92.0,Poland,POL,1992,Summer,Barcelona,Rowing,Single Sculls,Bronze
32883,16915,Everard Burnside Butler,M,26.0,183.0,72.0,Canada,CAN,1912,Summer,Stockholm,Rowing,Single Sculls,Bronze
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270986,135508,Vera Igorevna Zvonaryova,F,23.0,172.0,59.0,Russia,RUS,2008,Summer,Beijing,Tennis,Singles,Bronze
271032,135535,Claudia Antoinette Zwiers,F,22.0,181.0,78.0,Netherlands,NED,1996,Summer,Atlanta,Judo,Middleweight,Bronze
271076,135553,Galina Ivanovna Zybina (-Fyodorova),F,21.0,168.0,80.0,Soviet Union,URS,1952,Summer,Helsinki,Athletics,Shot Put,Gold
271078,135553,Galina Ivanovna Zybina (-Fyodorova),F,25.0,168.0,80.0,Soviet Union,URS,1956,Summer,Melbourne,Athletics,Shot Put,Silver
271080,135553,Galina Ivanovna Zybina (-Fyodorova),F,33.0,168.0,80.0,Soviet Union,URS,1964,Summer,Tokyo,Athletics,Shot Put,Bronze

In [59]:
## Arrondi à l'unité des colonnes 'Age' et 'height" ##

colonnes_arrondis = ['Age', 'Height']
for colonne in colonnes_arrondis:
    jo[colonne] = jo[colonne].astype(str).str.split('.').str[0].astype(int)
jo

C:\Users\molon\AppData\Local\Temp\ipykernel_18440\252002162.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  jo[colonne] = jo[colonne].astype(str).str.split('.').str[0].astype(int)
C:\Users\molon\AppData\Local\Temp\ipykernel_18440\252002162.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  jo[colonne] = jo[colonne].astype(str).str.split('.').str[0].astype(int)

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Year,Season,City,Sport,Event,Medal
8318,4587,Yelena Petrovna Antonova,F,23,180,78.0,Soviet Union,URS,1976,Summer,Montreal,Rowing,Single Sculls,Bronze
17710,9421,Jutta Behrendt (Hampe-),F,27,181,75.0,East Germany,GDR,1988,Summer,Seoul,Rowing,Single Sculls,Gold
28647,14846,Annelies Bredael,F,27,175,68.0,Belgium,BEL,1992,Summer,Barcelona,Rowing,Single Sculls,Silver
29717,15344,Kajetan Tomasz Broniewski,M,29,187,92.0,Poland,POL,1992,Summer,Barcelona,Rowing,Single Sculls,Bronze
32883,16915,Everard Burnside Butler,M,26,183,72.0,Canada,CAN,1912,Summer,Stockholm,Rowing,Single Sculls,Bronze
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270986,135508,Vera Igorevna Zvonaryova,F,23,172,59.0,Russia,RUS,2008,Summer,Beijing,Tennis,Singles,Bronze
271032,135535,Claudia Antoinette Zwiers,F,22,181,78.0,Netherlands,NED,1996,Summer,Atlanta,Judo,Middleweight,Bronze
271076,135553,Galina Ivanovna Zybina (-Fyodorova),F,21,168,80.0,Soviet Union,URS,1952,Summer,Helsinki,Athletics,Shot Put,Gold
271078,135553,Galina Ivanovna Zybina (-Fyodorova),F,25,168,80.0,Soviet Union,URS,1956,Summer,Melbourne,Athletics,Shot Put,Silver
271080,135553,Galina Ivanovna Zybina (-Fyodorova),F,33,168,80.0,Soviet Union,URS,1964,Summer,Tokyo,Athletics,Shot Put,Bronze

In [60]:
## tri du dataset par la colonne 'ID' ##

jo = jo.sort_values(by='ID', ascending = True)
jo

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Year,Season,City,Sport,Event,Medal
44,17,Paavo Johannes Aaltonen,M,28,175,64.0,Finland,FIN,1948,Summer,London,Gymnastics,Horse Vault,Gold
48,17,Paavo Johannes Aaltonen,M,28,175,64.0,Finland,FIN,1948,Summer,London,Gymnastics,Pommelled Horse,Gold
41,17,Paavo Johannes Aaltonen,M,28,175,64.0,Finland,FIN,1948,Summer,London,Gymnastics,Individual All-Around,Bronze
159,63,Jos Luis Abajo Gmez,M,30,194,87.0,Spain,ESP,2008,Summer,Beijing,Fencing,"epee, Individual",Bronze
161,65,Patimat Abakarova,F,21,165,49.0,Azerbaijan,AZE,2016,Summer,Rio de Janeiro,Taekwondo,Flyweight,Bronze
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270986,135508,Vera Igorevna Zvonaryova,F,23,172,59.0,Russia,RUS,2008,Summer,Beijing,Tennis,Singles,Bronze
271032,135535,Claudia Antoinette Zwiers,F,22,181,78.0,Netherlands,NED,1996,Summer,Atlanta,Judo,Middleweight,Bronze
271078,135553,Galina Ivanovna Zybina (-Fyodorova),F,25,168,80.0,Soviet Union,URS,1956,Summer,Melbourne,Athletics,Shot Put,Silver
271076,135553,Galina Ivanovna Zybina (-Fyodorova),F,21,168,80.0,Soviet Union,URS,1952,Summer,Helsinki,Athletics,Shot Put,Gold
271080,135553,Galina Ivanovna Zybina (-Fyodorova),F,33,168,80.0,Soviet Union,URS,1964,Summer,Tokyo,Athletics,Shot Put,Bronze

In [61]:
## Suppression des lignes avant 1952 ##

jo = jo[jo['Year'] >= 1952]
jo

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Year,Season,City,Sport,Event,Medal
159,63,Jos Luis Abajo Gmez,M,30,194,87.0,Spain,ESP,2008,Summer,Beijing,Fencing,"epee, Individual",Bronze
161,65,Patimat Abakarova,F,21,165,49.0,Azerbaijan,AZE,2016,Summer,Rio de Janeiro,Taekwondo,Flyweight,Bronze
163,67,Mariya Vasilyevna Abakumova (-Tarabina),F,22,179,80.0,Russia,RUS,2008,Summer,Beijing,Athletics,Javelin Throw,Silver
186,84,Stephen Anthony Abas,M,26,165,55.0,United States,USA,2004,Summer,Athina,Wrestling,"Featherweight, Freestyle",Silver
191,86,Jos Manuel Abascal Gmez,M,26,182,67.0,Spain,ESP,1984,Summer,Los Angeles,Athletics,"1,500 metres",Bronze
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270986,135508,Vera Igorevna Zvonaryova,F,23,172,59.0,Russia,RUS,2008,Summer,Beijing,Tennis,Singles,Bronze
271032,135535,Claudia Antoinette Zwiers,F,22,181,78.0,Netherlands,NED,1996,Summer,Atlanta,Judo,Middleweight,Bronze
271078,135553,Galina Ivanovna Zybina (-Fyodorova),F,25,168,80.0,Soviet Union,URS,1956,Summer,Melbourne,Athletics,Shot Put,Silver
271076,135553,Galina Ivanovna Zybina (-Fyodorova),F,21,168,80.0,Soviet Union,URS,1952,Summer,Helsinki,Athletics,Shot Put,Gold
271080,135553,Galina Ivanovna Zybina (-Fyodorova),F,33,168,80.0,Soviet Union,URS,1964,Summer,Tokyo,Athletics,Shot Put,Bronze

In [62]:
## calcul de l'IMC par ligne et ajout du résultat dans une nouvelle colonne ##

jo['IMC'] = jo['Weight'] / (jo['Height'] / 100) ** 2
jo

C:\Users\molon\AppData\Local\Temp\ipykernel_18440\3890072841.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  jo['IMC'] = jo['Weight'] / (jo['Height'] / 100) ** 2

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Year,Season,City,Sport,Event,Medal,IMC
159,63,Jos Luis Abajo Gmez,M,30,194,87.0,Spain,ESP,2008,Summer,Beijing,Fencing,"epee, Individual",Bronze,23.116165
161,65,Patimat Abakarova,F,21,165,49.0,Azerbaijan,AZE,2016,Summer,Rio de Janeiro,Taekwondo,Flyweight,Bronze,17.998163
163,67,Mariya Vasilyevna Abakumova (-Tarabina),F,22,179,80.0,Russia,RUS,2008,Summer,Beijing,Athletics,Javelin Throw,Silver,24.968010
186,84,Stephen Anthony Abas,M,26,165,55.0,United States,USA,2004,Summer,Athina,Wrestling,"Featherweight, Freestyle",Silver,20.202020
191,86,Jos Manuel Abascal Gmez,M,26,182,67.0,Spain,ESP,1984,Summer,Los Angeles,Athletics,"1,500 metres",Bronze,20.227026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270986,135508,Vera Igorevna Zvonaryova,F,23,172,59.0,Russia,RUS,2008,Summer,Beijing,Tennis,Singles,Bronze,19.943213
271032,135535,Claudia Antoinette Zwiers,F,22,181,78.0,Netherlands,NED,1996,Summer,Atlanta,Judo,Middleweight,Bronze,23.808797
271078,135553,Galina Ivanovna Zybina (-Fyodorova),F,25,168,80.0,Soviet Union,URS,1956,Summer,Melbourne,Athletics,Shot Put,Silver,28.344671
271076,135553,Galina Ivanovna Zybina (-Fyodorova),F,21,168,80.0,Soviet Union,URS,1952,Summer,Helsinki,Athletics,Shot Put,Gold,28.344671
271080,135553,Galina Ivanovna Zybina (-Fyodorova),F,33,168,80.0,Soviet Union,URS,1964,Summer,Tokyo,Athletics,Shot Put,Bronze,28.344671

In [63]:
## Limiter à deux décimales la colonne "IMC"  ##

jo['IMC'] = jo['IMC'].round(2)
jo

C:\Users\molon\AppData\Local\Temp\ipykernel_18440\4105428998.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  jo['IMC'] = jo['IMC'].round(2)

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Year,Season,City,Sport,Event,Medal,IMC
159,63,Jos Luis Abajo Gmez,M,30,194,87.0,Spain,ESP,2008,Summer,Beijing,Fencing,"epee, Individual",Bronze,23.12
161,65,Patimat Abakarova,F,21,165,49.0,Azerbaijan,AZE,2016,Summer,Rio de Janeiro,Taekwondo,Flyweight,Bronze,18.00
163,67,Mariya Vasilyevna Abakumova (-Tarabina),F,22,179,80.0,Russia,RUS,2008,Summer,Beijing,Athletics,Javelin Throw,Silver,24.97
186,84,Stephen Anthony Abas,M,26,165,55.0,United States,USA,2004,Summer,Athina,Wrestling,"Featherweight, Freestyle",Silver,20.20
191,86,Jos Manuel Abascal Gmez,M,26,182,67.0,Spain,ESP,1984,Summer,Los Angeles,Athletics,"1,500 metres",Bronze,20.23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270986,135508,Vera Igorevna Zvonaryova,F,23,172,59.0,Russia,RUS,2008,Summer,Beijing,Tennis,Singles,Bronze,19.94
271032,135535,Claudia Antoinette Zwiers,F,22,181,78.0,Netherlands,NED,1996,Summer,Atlanta,Judo,Middleweight,Bronze,23.81
271078,135553,Galina Ivanovna Zybina (-Fyodorova),F,25,168,80.0,Soviet Union,URS,1956,Summer,Melbourne,Athletics,Shot Put,Silver,28.34
271076,135553,Galina Ivanovna Zybina (-Fyodorova),F,21,168,80.0,Soviet Union,URS,1952,Summer,Helsinki,Athletics,Shot Put,Gold,28.34
271080,135553,Galina Ivanovna Zybina (-Fyodorova),F,33,168,80.0,Soviet Union,URS,1964,Summer,Tokyo,Athletics,Shot Put,Bronze,28.34

In [64]:
## déplacer la colonne IMC à coté de la colonne Weight ##

col_to_move = 'IMC'
new_index = 6
cols = list(jo.columns)
cols.insert(new_index, cols.pop(cols.index(col_to_move)))
jo = jo[cols]
jo

,ID,Name,Sex,Age,Height,Weight,IMC,Team,NOC,Year,Season,City,Sport,Event,Medal
159,63,Jos Luis Abajo Gmez,M,30,194,87.0,23.12,Spain,ESP,2008,Summer,Beijing,Fencing,"epee, Individual",Bronze
161,65,Patimat Abakarova,F,21,165,49.0,18.00,Azerbaijan,AZE,2016,Summer,Rio de Janeiro,Taekwondo,Flyweight,Bronze
163,67,Mariya Vasilyevna Abakumova (-Tarabina),F,22,179,80.0,24.97,Russia,RUS,2008,Summer,Beijing,Athletics,Javelin Throw,Silver
186,84,Stephen Anthony Abas,M,26,165,55.0,20.20,United States,USA,2004,Summer,Athina,Wrestling,"Featherweight, Freestyle",Silver
191,86,Jos Manuel Abascal Gmez,M,26,182,67.0,20.23,Spain,ESP,1984,Summer,Los Angeles,Athletics,"1,500 metres",Bronze
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270986,135508,Vera Igorevna Zvonaryova,F,23,172,59.0,19.94,Russia,RUS,2008,Summer,Beijing,Tennis,Singles,Bronze
271032,135535,Claudia Antoinette Zwiers,F,22,181,78.0,23.81,Netherlands,NED,1996,Summer,Atlanta,Judo,Middleweight,Bronze
271078,135553,Galina Ivanovna Zybina (-Fyodorova),F,25,168,80.0,28.34,Soviet Union,URS,1956,Summer,Melbourne,Athletics,Shot Put,Silver
271076,135553,Galina Ivanovna Zybina (-Fyodorova),F,21,168,80.0,28.34,Soviet Union,URS,1952,Summer,Helsinki,Athletics,Shot Put,Gold
271080,135553,Galina Ivanovna Zybina (-Fyodorova),F,33,168,80.0,28.34,Soviet Union,URS,1964,Summer,Tokyo,Athletics,Shot Put,Bronze

In [65]:
## Visualisation du nombre de lignes par Event ##

event_counts = jo['Event'].value_counts()
print(event_counts)

Event
Heavyweight                        225
Middleweight                       203
Lightweight                        199
Individual                         187
Featherweight                      153
                                  ...
500 metres Time Trial                6
Running Target, 50 metres            6
Canadian Singles, 10,000 metres      3
Kayak Singles, 10,000 metres         2
Jumping, Individual                  2
Name: count, Length: 139, dtype: int64

In [66]:
## Suppression des Event ayant 10 linges ou moins ##

events_to_keep = event_counts[event_counts >= 10].index
jo = jo[jo['Event'].isin(events_to_keep)]
jo

,ID,Name,Sex,Age,Height,Weight,IMC,Team,NOC,Year,Season,City,Sport,Event,Medal
159,63,Jos Luis Abajo Gmez,M,30,194,87.0,23.12,Spain,ESP,2008,Summer,Beijing,Fencing,"epee, Individual",Bronze
161,65,Patimat Abakarova,F,21,165,49.0,18.00,Azerbaijan,AZE,2016,Summer,Rio de Janeiro,Taekwondo,Flyweight,Bronze
163,67,Mariya Vasilyevna Abakumova (-Tarabina),F,22,179,80.0,24.97,Russia,RUS,2008,Summer,Beijing,Athletics,Javelin Throw,Silver
186,84,Stephen Anthony Abas,M,26,165,55.0,20.20,United States,USA,2004,Summer,Athina,Wrestling,"Featherweight, Freestyle",Silver
191,86,Jos Manuel Abascal Gmez,M,26,182,67.0,20.23,Spain,ESP,1984,Summer,Los Angeles,Athletics,"1,500 metres",Bronze
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270986,135508,Vera Igorevna Zvonaryova,F,23,172,59.0,19.94,Russia,RUS,2008,Summer,Beijing,Tennis,Singles,Bronze
271032,135535,Claudia Antoinette Zwiers,F,22,181,78.0,23.81,Netherlands,NED,1996,Summer,Atlanta,Judo,Middleweight,Bronze
271078,135553,Galina Ivanovna Zybina (-Fyodorova),F,25,168,80.0,28.34,Soviet Union,URS,1956,Summer,Melbourne,Athletics,Shot Put,Silver
271076,135553,Galina Ivanovna Zybina (-Fyodorova),F,21,168,80.0,28.34,Soviet Union,URS,1952,Summer,Helsinki,Athletics,Shot Put,Gold
271080,135553,Galina Ivanovna Zybina (-Fyodorova),F,33,168,80.0,28.34,Soviet Union,URS,1964,Summer,Tokyo,Athletics,Shot Put,Bronze

In [67]:
## Visualisation du nombre de lignes par Event ##

event_counts = jo['Event'].value_counts()
print(event_counts)

Event
Heavyweight                  225
Middleweight                 203
Lightweight                  199
Individual                   187
Featherweight                153
                            ...
Kayak Singles, 200 metres     13
Heavyweight I                 13
Heavyweight II                12
Omnium                        12
Running Target, 10 metres     11
Name: count, Length: 130, dtype: int64

In [68]:
## Recherche et visualisation des éventuels doublons ##

duplicateRows = jo[jo.duplicated()]
duplicateRows

Empty DataFrame
Columns: [ID, Name, Sex, Age, Height, Weight, IMC, Team, NOC, Year, Season, City, Sport, Event, Medal]
Index: []

In [69]:
## Visualisation des statistiques descriptives de l'ensemble des données ##

jo.describe(include="all")

,ID,Name,Sex,Age,Height,Weight,IMC,Team,NOC,Year,Season,City,Sport,Event,Medal
count,8250.000000,8250,8250,8250.000000,8250.000000,8250.000000,8250.000000,8250,8250,8250.000000,8250,8250,8250,8250,8250
unique,NaN,6055,2,NaN,NaN,NaN,NaN,135,135,NaN,1,17,24,130,3
top,NaN,"Michael Fred Phelps, II",M,NaN,NaN,NaN,NaN,United States,USA,NaN,Summer,Rio de Janeiro,Athletics,Heavyweight,Bronze
freq,NaN,16,5537,NaN,NaN,NaN,NaN,1183,1183,NaN,8250,707,1850,225,2999
mean,70523.840000,NaN,NaN,24.729212,174.868727,72.127576,23.326258,NaN,NaN,1990.641455,NaN,NaN,NaN,NaN,NaN
std,38822.712085,NaN,NaN,4.710031,11.050358,17.898762,3.998940,NaN,NaN,18.146604,NaN,NaN,NaN,NaN,NaN
min,63.000000,NaN,NaN,13.000000,136.000000,28.000000,14.880000,NaN,NaN,1952.000000,NaN,NaN,NaN,NaN,NaN
25%,38234.750000,NaN,NaN,22.000000,167.000000,60.000000,20.820000,NaN,NaN,1976.000000,NaN,NaN,NaN,NaN,NaN
50%,70156.500000,NaN,NaN,24.000000,175.000000,70.000000,22.590000,NaN,NaN,1992.000000,NaN,NaN,NaN,NaN,NaN
75%,104095.000000,NaN,NaN,27.000000,183.000000,81.000000,24.800000,NaN,NaN,2008.000000,NaN,NaN,NaN,NaN,NaN
max,135553.000000,NaN,NaN,58.000000,214.000000,182.000000,56.500000,NaN,NaN,2016.000000,NaN,NaN,NaN,NaN,NaN

In [70]:
jo.to_csv('athlete_events_clean.csv', index=False)